name: Build Mu

on:
  push:
    branches: 'master'
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Display Python info
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import platform, struct; print(platform.machine(), struct.calcsize('P') * 8)"
          python -c "import sys; print(sys.executable)"
          python -m pip --version
          pip --version
          pip config list
          pip freeze
      - name: Install Mu test dependencies
        run: |
          pip install .[tests]
          pip list
      - run: mkdir upload
      - name: Build Windows 64 bit
        if: runner.os == 'Windows'
        run: |
          python make.py win64
          dir dist/*.msi | rename-item -newname {  $_.name  -replace ".msi"," (64 bit).msi"  }
          mv dist/*.msi upload/
      - name: Build macOS
        if: runner.os == 'macOS'
        run: |
          make macos
          mv dist/*.dmg upload/
      - name: Upload Mu installer
        uses: actions/upload-artifact@v1
        with:
          name: mu-editor-${{ runner.os }}-${{ github.sha }}
          path: upload

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    name: Build AppImage
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        run: |
          apt-get update
          apt-get install -y wget make
          wget https://github.com/indygreg/python-build-standalone/releases/download/20220502/cpython-3.8.13+20220502-x86_64-unknown-linux-gnu-install_only.tar.gz
          tar -xf cpython-3.8.13+20220502-x86_64-unknown-linux-gnu-install_only.tar.gz -C /
          ln -s /python/bin/python3.8 /bin/python
          ln -s /python/bin/python3.8 /bin/python3
          ln -s /python/bin/python3.8 /bin/python3.8
          ln -s /python/bin/pip /bin/pip
      - name: Display Python info
        run: |
          uname -a
          python -c "import sys; print(sys.version)"
          python -c "import platform, struct; print(platform.machine(), struct.calcsize('P') * 8)"
          python -c "import sys; print(sys.executable)"
          python -m pip --version
          pip --version
          pip config list
          pip list --verbose
      - name: Install xvfb
        run: apt-get install -y libxkbcommon-x11-0 xvfb
      # Install this dependency as a workaround to PyQt5 issue
      # qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
      - name: Install PyQt5 issue workaround
        run: apt install -y libqt5gui5
      - name: Install AppImage dependencies
        run: apt-get -y install file appstream
      - name: Install Mu test dependencies
        run: |
          pip install .[tests]
          pip list
      - run: mkdir upload
      - name: Build Linux AppImage
        run: xvfb-run make linux
      # GitHub actions upload artifact breaks permissions, so tar workaround
      # https://github.com/actions/upload-artifact/issues/38
      - name: Tar AppImage to maintain permissions
        run: |
          cd dist/
          tar -cvf Mu_Editor-AppImage-x86_64-${{ github.sha }}.tar *.AppImage
          ls -la .
      - name: Upload Mu AppImage
        uses: actions/upload-artifact@v1
        with:
          name: mu-editor-${{ runner.os }}-${{ github.sha }}
          path: dist/Mu_Editor-AppImage-x86_64-${{ github.sha }}.tar
